maindesc: Colectividad libre de Atenas
banner: Επόμενο live σήμερα 14/05 στις 21.30
browsercompatibility: "Συμβάτοι browsers για ακρόαση: Firefox, Opera, Internet
  Explorer και DuckDuckGo. Για να ακούσετε σε Google Chrome χρειάζεται από το
  site settings στο Insecure content να επιλέξετε Allow."
news: News
music: Music
social: Κοινωνικά
art: Art & Cinema
sansimera: Σαν Σήμερα
