maindesc: Colectividad libre de Atenas
banner: Σε λίγο ακολουθεί το ιδρυτικό κείμενο της συλλογικότητας CoLibre
browsercompatibility: "Συμβάτοι browsers για ακρόαση: Firefox, Internet Explorer
  και DuckDuckGo. Για να ακούσετε σε Google Chrome χρειάζεται από το site
  settings στο Insecure content να επιλέξετε Allow."
