maindesc: "New location: www.colibreradio.com"
banner: ""
browsercompatibility: "Συμβάτοι για ακροάση είναι όλοι οι browsers και οι mobile συσκευές."
news: News
music: Music
social: Κοινωνικά
art: Art & Cinema
sansimera: Σαν Σήμερα
