maindesc: Colectividad libre de Atenas
banner: Δείτε τώρα το ντοκιμαντέρ μικρού μήκους το οποίο επιμελήθηκαν οι Dario
  Azzellini και Oliver Ressler με τον τίτλο "ΚΑΤΑΛΗΨΗ-ΑΝΤΙΣΤΑΣΗ-ΠΑΡΑΓΩΓΗ"
  https://www.facebook.com/watch/live/?v=165867614762808&ref=notif&notif_id=1588186912140406&notif_t=live_video
browsercompatibility: "Συμβάτοι browsers για ακρόαση: Firefox, Internet Explorer
  και DuckDuckGo. Για να ακούσετε σε Google Chrome χρειάζεται από το site
  settings στο Insecure content να επιλέξετε Allow."
