maindesc: Colectividad libre from Athens
banner: ""
browsercompatibility: "Συμβάτοι browsers για ακρόαση: Firefox, Internet Explorer
  και DuckDuckGo. Για να ακούσετε σε Google Chrome χρειάζεται από το site
  settings στο Insecure content να επιλέξετε Allow."
